export enum UserRole {
  DONOR = "DONOR",
  INDIVIDUAL_ORGANIZER = "INDIVIDUAL_ORGANIZER",
  NGO_ORGANIZER = "NGO_ORGANIZER",
  VENDOR = "VENDOR",
  ADMIN = "ADMIN",
  REVIEWER = "REVIEWER",
  CSR_TEAM = "CSR_TEAM",
}

export enum CampaignStatus {
  DRAFT = "DRAFT",
  PENDING_REVIEW = "PENDING_REVIEW",
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  REJECTED = "REJECTED",
}

export enum MilestoneStatus {
  PENDING = "PENDING",
  OPEN = "OPEN",
  IN_REVIEW = "IN_REVIEW",
  APPROVED = "APPROVED",
  RELEASED = "RELEASED",
  REJECTED = "REJECTED",
}

export enum WithdrawalStatus {
  PENDING = "PENDING",
  SUBMITTED = "SUBMITTED",
  IN_REVIEW = "IN_REVIEW",
  APPROVED = "APPROVED",
  APPROVED_PENDING_PAYOUT = "APPROVED_PENDING_PAYOUT", // Approved but payout needs manual processing
  REJECTED = "REJECTED",
  RELEASED = "RELEASED",
}

export enum DonationType {
  INR = "INR",
  CRYPTO = "CRYPTO",
}

export enum EvidenceKind {
  INR_DONATION = "INR_DONATION",
  WITHDRAWAL_REQUEST = "WITHDRAWAL_REQUEST",
  MILESTONE_PROOF = "MILESTONE_PROOF",
}

export enum KYCStatus {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
}

export enum TokenType {
  INR = "INR", // For INR withdrawals
  USDC = "USDC",
  USDT = "USDT",
  NATIVE = "NATIVE",
  OTHER = "OTHER",
}

export enum ExpenseCategory {
  MATERIALS = "MATERIALS",
  SERVICES = "SERVICES",
  EDUCATION = "EDUCATION",
  HEALTHCARE = "HEALTHCARE",
  INFRASTRUCTURE = "INFRASTRUCTURE",
  ADMINISTRATIVE = "ADMINISTRATIVE",
  MARKETING = "MARKETING",
  OTHER = "OTHER",
}

export enum DocumentType {
  GST_TAX_INVOICE = "GST_TAX_INVOICE",
  RECEIPT = "RECEIPT",
  QUOTATION = "QUOTATION",
  PAYMENT_PROOF = "PAYMENT_PROOF",
  INSTITUTION_VERIFICATION = "INSTITUTION_VERIFICATION",
  PHOTO_VIDEO = "PHOTO_VIDEO",
  CONTRACT = "CONTRACT",
  OTHER = "OTHER",
}


